### ISSUE TITLE
Make the group titles bold? 

### ISSUE THREAD

**Issue by torian257x** [gojutin/tailwindcss-cheatsheet#1]
usually I would be scanning for say, text color

or text decoration, font weight etc but most likely not typography

is it possible to make the mini group headers bold?

great cheat sheet! much better than the original, I think the original maker doesnt know what a cheat sheet is.
The dumped the entire docs there...

**Comment by just214** [comment]
Hi and thanks for the feedback!  I just updated the cheatsheet with bolder fonts and the latest TailwindCSS changes. Hope you like the changes!
