### ISSUE TITLE
Output to a PDF?

### ISSUE THREAD

**Issue by julien-c** [gojutin/tailwindcss-cheatsheet#2]
To have a zoomable, vector version.

**Comment by just214** [comment]
Hi @julien-c - When I release an update for Tailwind 2, I will be sure to include a scalable, vector version. Thanks for the recommendation!

**Comment by julien-c** [comment]
Awesome, looking forward to it!

**Comment by just214** [comment]
Hello all. I don't know when/if I will get around to updating this cheatsheet for Tailwind 2.x. With v3 now on the horizon, there's a lot of changes to consider and sort through. And honestly, I don't know that I can fit the entire API on a single page any longer.

**Comment by just214** [comment]
I am not sure when I will get around to updating for ~~V2~~ V3, so I went ahead an added PDF and PNG exports for the current version (V1). I'll make sure and  always include these formats moving forward.
