### ISSUE TITLE
somehow jpg isnt sharp when printed with laserprinter

### ISSUE THREAD

**Issue by torian257x** [gojutin/tailwindcss-cheatsheet#3]
doesnt look crisp at all.
 
Any ideas?

**Comment by just214** [comment]
Hi, sorry to hear about the printing troubles. I added a PNG version (without transparency). Hopefully that helps. If not, you can always download the PSD file and export in whatever format you need. 

Please also keep in mind that this cheatsheet is rather dated at this point (V1). I was going to update to V3, but there is no way I can fit all that on a page! Maybe I'll go for a two page cheatsheet at some point.

**Comment by torian257x** [comment]
well even if not newest version, certainly helps a lot

I attach how it looks when i print it.

This is the new png version
is A4
I dont own photoshop
so not sure? is there maybe a way you can export it as pdf? maybe that stops the anti aliasing?


![20220325161607_001](https://user-images.githubusercontent.com/2072058/160150765-e02c1259-dbff-4f74-ba7d-e3f60d80b702.jpg)

**Comment by just214** [comment]
oh yikes...that's rough :/ I uploaded a PDF version earlier today. Can you try that and let me know?

**Comment by torian257x** [comment]
sooo the pdf was an improvement without doing any further changes apart from printing the pdf.

What I then later saw is that I can up the resolution of 600 dpi to 1200dpi (printer is new, not sure why they default low res). This increased prints as well. But: black white printer still cannot deal well with the red. Still just gives a dotty writing. Surprises me a bit, one would expect that they manage to just put a bit less toner on the paper.

Maybe release a black and white version that are black and white laser printer friendly one day? isnt urgent though. Wouldnt be able to tell what grey is black and white printer friendly either... 
actually... reading here:
https://www.quora.com/How-does-a-laser-printer-achieve-different-shades-of-gray

i guess the answer is a darker grey.


i actually have like 18 printouts of your cheatsheet XD

**Comment by just214** [comment]
Glad to hear the pdf worked out. When I eventually create the V3 cheatsheet, I'll make sure to include a grayscale option.

https://www.makeuseof.com/tag/dont-throw-that-old-printout-away-21-projects-for-used-paper/ 🙂
